sudo: true
services:
  - docker

language: scala

scala:
  - 2.12.3

jdk:
  - openjdk8

script:
  - sbt test

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
